dependencies {

    api("com.cleanroommc:modularui:3.0.3") { transitive = false }
    api("codechicken:codechickenlib:3.2.3.358")
    api("com.cleanroommc:groovyscript:1.2.5") { transitive = false }

    compileOnly("gregtech:gregtech:2.8.10-beta")
    compileOnly(rfg.deobf("com.azanor.baubles:Baubles:1.12-1.5.2"))

    implementation("mezz.jei:jei_1.12.2:4.16.1.302")
    implementation(rfg.deobf("curse.maven:top-245211:2667280")) // TOP 1.4.28

    compileOnly("org.jetbrains:annotations:26.0.2-1")
    testImplementation("io.kotest:kotest-runner-junit5:5.9.1")
    testImplementation("io.mockk:mockk:1.14.5")

}