feature:
  - head-branch: ['^feature', 'feature']
bug:
  - head-branch: ['^fix', 'fix']
refactoring:
  - head-branch: ['^refactor', 'refactor']
"ignore changelog":
  - head-branch: ['^ignorec', 'ignorec']