changelog:
  exclude:
    labels:
      - "ignore changelog"

  categories:
    - title: Added
      labels:
        - "type: feature"
    - title: Fixed
      labels:
        - "type: bug"
    - title: "Other Changes"
      labels:
        - "*"