package io.github.trcdevelopers.clayium.api.unification.material

// TODO: Move these to CMaterials
@Suppress("SpellCheckingInspection")
object CMarkerMaterials {
    val obsidian = CMarkerMaterial("Obsidian")
    val diamond = CMarkerMaterial("Diamond")
    val emerald  = CMarkerMaterial("Emerald")

    val apatite = CMarkerMaterial("Apatite")
    val topaz = CMarkerMaterial("Topaz")
    val malachite = CMarkerMaterial("Malachite")
    val tanzanite  = CMarkerMaterial("Tanzanite")
    val dilithium = CMarkerMaterial("Dilithium")
    val forcicium = CMarkerMaterial("Forcicium")

    val signalum = CMarkerMaterial("Signalum")
    val lumium = CMarkerMaterial("Lumium")
    val electrumFlux = CMarkerMaterial("ElectrumFlux")
    val crystalFlux = CMarkerMaterial("CrystalFlux")

    val certusQuartz = CMarkerMaterial("CertusQuartz")
    val fluix = CMarkerMaterial("Fluix")
    val redstoneAlloy = CMarkerMaterial("RedstoneAlloy")
    val conductiveIron = CMarkerMaterial("ConductiveIron")
    val energeticAlloy = CMarkerMaterial("EnergeticAlloy")
    val electricalSteel = CMarkerMaterial("ElectricalSteel")
    val darkSteel = CMarkerMaterial("DarkSteel")
    val pulsatingIron = CMarkerMaterial("PulsatingIron")
    val vibrantAlloy = CMarkerMaterial("VibrantAlloy")
    val soularium = CMarkerMaterial("Soularium")

    val glass = CMarkerMaterial("Glass")

    val yellorium = CMarkerMaterial("Yellorium")
    val cyanite = CMarkerMaterial("Cyanite")
    val blutonium = CMarkerMaterial("Blutonium")
    val ludicrite = CMarkerMaterial("Ludicrite")

    val refinedGlowstone = CMarkerMaterial("RefinedGlowstone")
    val refinedObsidian  = CMarkerMaterial("RefinedObsidian")

    val ardite  = CMarkerMaterial("Ardite")
    val aluminumBrass = CMarkerMaterial("Alubrass")
    val alumite  = CMarkerMaterial("Alumite")
    val manyullyn = CMarkerMaterial("Manyullyn")
    val pigiron = CMarkerMaterial("Pigiron")
    val pokefennium = CMarkerMaterial("Pokefennium")
    val fairy = CMarkerMaterial("Fairy")

    val electrotine  = CMarkerMaterial("Electrotine")
    val electrotineAlloy  = CMarkerMaterial("ElectrotineAlloy")
    val redAlloy  = CMarkerMaterial("RedAlloy")

    val meteoricIron = CMarkerMaterial("MeteoricIron")
    val desh = CMarkerMaterial("Desh")

    // metallurgy
    val deepIron = CMarkerMaterial("DeepIron")
    val prometheum = CMarkerMaterial("Prometheum")
    val infuscolium = CMarkerMaterial("Infuscolium")
    val oureclase = CMarkerMaterial("Oureclase")
    val astralSilver = CMarkerMaterial("AstralSilver")
    val carmot = CMarkerMaterial("Cartmot")
    val mithril = CMarkerMaterial("Mithril")
    val rubracium = CMarkerMaterial("Rubracium")
    val orichalcum = CMarkerMaterial("Orichalcum")
    val adamatine  = CMarkerMaterial("Adamatine")
    val atlarus = CMarkerMaterial("Atlarus")
    val ignatius = CMarkerMaterial("Ignatius")
    val shadowIron = CMarkerMaterial("ShadowIron")
    val lemurite = CMarkerMaterial("Lemurite")
    val midasium = CMarkerMaterial("Midasium")
    val vyroxeres = CMarkerMaterial("Vyroxeres")
    val ceruclase  = CMarkerMaterial("Ceruclase")
    val alduorite  = CMarkerMaterial("Alduorite")
    val kalendrite = CMarkerMaterial("Kalendrite")
    val vulcanite  = CMarkerMaterial("Vulcanite")
    val sanguinite  = CMarkerMaterial("Sanguinite")
    val eximite  = CMarkerMaterial("Eximite")
    val meutoite  = CMarkerMaterial("Meutoite")
    val hepatizon = CMarkerMaterial("Hepatizon")
    val damascusSteel = CMarkerMaterial("DamascusSteel")
    val angmallen  = CMarkerMaterial("Angmallen")
    val blackSteel = CMarkerMaterial("BlackSteel")
    val quickSilver = CMarkerMaterial("QuickSilver")
    val haderoth = CMarkerMaterial("Haderoth")
    val celenegil = CMarkerMaterial("Celenegil")
    val tartarite  = CMarkerMaterial("Tartarite")
    val shadowSteel = CMarkerMaterial("ShadowSteel")
    val inolashite  = CMarkerMaterial("Inolashite")
    val amordrine  = CMarkerMaterial("Amordrine")
    val desichalkos = CMarkerMaterial("Desichalkos")

    val white = CMarkerMaterial("White")
    val orange = CMarkerMaterial("Orange")
    val magenta = CMarkerMaterial("Magenta")
    val lightBlue = CMarkerMaterial("LightBlue")
    val yellow = CMarkerMaterial("Yellow")
    val lime = CMarkerMaterial("Lime")
    val pink = CMarkerMaterial("Pink")
    val gray = CMarkerMaterial("Gray")
    val lightGray = CMarkerMaterial("LightGray")
    val cyan = CMarkerMaterial("Cyan")
    val purple = CMarkerMaterial("Purple")
    val blue = CMarkerMaterial("Blue")
    val brown = CMarkerMaterial("Brown")
    val green = CMarkerMaterial("Green")
    val red = CMarkerMaterial("Red")
    val black = CMarkerMaterial("Black")

    fun init() {}
}