name: Crash Report
description: Report a bug that crashes the game or prevents startup.
labels: [ "status: unverified", "bug", "high priority" ]
body:
  - type: input
    id: version
    attributes:
      label: Mod Version
      description: The version of Clayium Unofficial you were using when this bug was encountered. If you do not know where to find this, look for the mod jar file in the mods folder, or in the mods viewer in-game.
      placeholder: "vX.Y.Z"
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: "How you were playing on the world. Typical answers include: Singleplayer, Open to LAN, Forge Server, Sponge Server, or Mohist Server."
      placeholder: "Example: Singleplayer"
    validations:
      required: true
  - type: dropdown
    id: crash
    attributes:
      label: Side Crashed
      description: Where the game crashed.
      options:
        - "Client"
        - "Server"
        - "Client and Server"
        - "Unsure"
    validations:
      required: true
  - type: dropdown
    id: world
    attributes:
      label: New Worlds
      description: Does this crash occur on a newly generated world?
      options:
        - "Yes"
        - "No"
        - "Unsure"
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How to reproduce the crash.
      placeholder: "Example: 1) I did X..."
    validations:
      required: true
  - type: textarea
    id: crash-report
    attributes:
      label: Crash Report
      description: "You can find the crash report in `installation/crash-reports/`, if one was created. Additionally, please attach `installation/logs/latest.log`. If either or both files do not exist, state such. Please link to a paste site with their content, such as mclo.gs, GitHub Gists or Pastebin. **Do not paste the contents of either these files directly into the text box.**"
      placeholder: "Example: a link to a paste site with the crash report and latest.log."
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any additional information you wish to provide. Please add anything which did not fit into the other sections here.
      placeholder: "Example: This is likely caused by X because..."
    validations:
      required: false
  - type: markdown
    attributes:
      value: Thank you for taking the time to fill out this crash report.