package io.github.trcdevelopers.clayium.common.loaders.recipe.integration.metallurgy

import io.github.trcdevelopers.clayium.api.unification.material.CMarkerMaterials
import io.github.trcdevelopers.clayium.api.unification.material.CMaterials
import io.github.trcdevelopers.clayium.api.unification.ore.OrePrefix
import io.github.trcdevelopers.clayium.common.recipe.registry.CRecipes

object MetallurgyRecipeLoader {
    fun registerRecipes() {
        val caInjector = CRecipes.CA_INJECTOR
        val matterTransformer = CRecipes.MATTER_TRANSFORMER
        val alloySmelter = CRecipes.ALLOY_SMELTER

        caInjector.builder()
            .input(OrePrefix.ingot, CMaterials.promethium)
            .inputAntimatter(1)
            .output(OrePrefix.ingot, CMarkerMaterials.prometheum)
            .tier(10).duration(60)
            .buildAndRegister()
        matterTransformer.builder()
            .defaultPrefix(OrePrefix.ingot).duration(200)
            .input(CMarkerMaterials.prometheum)
            .output(CMarkerMaterials.deepIron).tier(7)
            .chain(CMarkerMaterials.infuscolium)
            .chain(CMarkerMaterials.oureclase).tier(8)
            .chain(CMarkerMaterials.astralSilver).tier(9)
            .chain(CMarkerMaterials.carmot)
            .chain(CMarkerMaterials.mithril)
            .chain(CMarkerMaterials.rubracium).tier(10)
            .chain(CMarkerMaterials.orichalcum)
            .chain(CMarkerMaterials.adamatine).tier(11)
            .chain(CMarkerMaterials.atlarus)
            .buildAndRegister()

        caInjector.builder()
            .input(OrePrefix.ingot, CMaterials.rubidium)
            .inputAntimatter(1)
            .output(OrePrefix.ingot, CMarkerMaterials.ignatius)
            .tier(10).duration(60)
            .buildAndRegister()
        matterTransformer.builder()
            .defaultPrefix(OrePrefix.ingot).duration(200)
            .input(CMarkerMaterials.ignatius)
            .output(CMarkerMaterials.shadowIron).tier(7)
            .chain(CMarkerMaterials.lemurite)
            .chain(CMarkerMaterials.midasium).tier(8)
            .chain(CMarkerMaterials.vyroxeres)
            .chain(CMarkerMaterials.ceruclase)
            .chain(CMarkerMaterials.alduorite)
            .chain(CMarkerMaterials.kalendrite).tier(9)
            .chain(CMarkerMaterials.vulcanite).tier(10)
            .chain(CMarkerMaterials.sanguinite).tier(11)
            .buildAndRegister()

        caInjector.builder()
            .input(OrePrefix.ingot, CMaterials.protactinium)
            .inputAntimatter(1)
            .output(OrePrefix.ingot, CMarkerMaterials.eximite)
            .tier(10).duration(60)
            .buildAndRegister()
        matterTransformer.builder()
            .input(OrePrefix.ingot, CMarkerMaterials.eximite)
            .output(OrePrefix.ingot, CMarkerMaterials.meutoite)
            .tier(9).duration(200)
            .buildAndRegister()

        alloySmelter.builder()
            .input(CMaterials.bronze)
            .input(CMaterials.gold)
            .output(OrePrefix.ingot, CMarkerMaterials.hepatizon, 2)
            .tier(6).duration(100)
            .buildAndRegister()
        alloySmelter.builder()
            .input(CMaterials.bronze)
            .input(CMaterials.iron)
            .output(OrePrefix.ingot, CMarkerMaterials.damascusSteel, 2)
            .tier(6).duration(100)
            .buildAndRegister()
        alloySmelter.builder()
            .input(CMaterials.iron)
            .input(CMaterials.gold)
            .output(OrePrefix.ingot, CMarkerMaterials.angmallen, 2)
            .tier(6).duration(100)
            .buildAndRegister()
        alloySmelter.builder()
            .input(CMarkerMaterials.deepIron)
            .input(CMarkerMaterials.infuscolium)
            .output(OrePrefix.ingot, CMarkerMaterials.blackSteel, 2)
            .tier(6).duration(100)
            .buildAndRegister()
        alloySmelter.builder()
            .input(CMarkerMaterials.mithril)
            .input(CMaterials.silver)
            .output(OrePrefix.ingot, CMarkerMaterials.quickSilver, 2)
            .tier(6).duration(100)
            .buildAndRegister()
        alloySmelter.builder()
            .input(CMarkerMaterials.mithril)
            .input(CMarkerMaterials.rubracium)
            .output(OrePrefix.ingot, CMarkerMaterials.haderoth, 2)
            .tier(6).duration(100)
            .buildAndRegister()
        alloySmelter.builder()
            .input(CMarkerMaterials.orichalcum)
            .input(CMaterials.platinum)
            .output(OrePrefix.ingot, CMarkerMaterials.celenegil, 2)
            .tier(6).duration(100)
            .buildAndRegister()
        alloySmelter.builder()
            .input(CMarkerMaterials.adamatine)
            .input(CMarkerMaterials.atlarus)
            .output(OrePrefix.ingot, CMarkerMaterials.tartarite, 2)
            .tier(6).duration(100)
            .buildAndRegister()
        alloySmelter.builder()
            .input(CMarkerMaterials.shadowIron)
            .input(CMarkerMaterials.lemurite)
            .output(OrePrefix.ingot, CMarkerMaterials.shadowSteel, 2)
            .tier(6).duration(100)
            .buildAndRegister()
        alloySmelter.builder()
            .input(CMarkerMaterials.alduorite)
            .input(CMarkerMaterials.ceruclase)
            .output(OrePrefix.ingot, CMarkerMaterials.inolashite, 2)
            .tier(6).duration(100)
            .buildAndRegister()
        alloySmelter.builder()
            .input(CMarkerMaterials.kalendrite)
            .input(CMaterials.platinum)
            .output(OrePrefix.ingot, CMarkerMaterials.amordrine, 2)
            .tier(6).duration(100)
            .buildAndRegister()
        alloySmelter.builder()
            .input(CMarkerMaterials.eximite)
            .input(CMarkerMaterials.meutoite)
            .output(OrePrefix.ingot, CMarkerMaterials.desichalkos, 2)
            .tier(6).duration(100)
            .buildAndRegister()
    }
}