name: PR Labeler

on:
  pull_request:
    types: [opened]

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pul-requests: write
    steps:
      - name: PR Labeler
        uses: actions/labeler@v5