# Copied & modified from GTCEu actions.
# https://github.com/GregTechCEu/GregTech/blob/master/.github/workflows/manage_pr_labels.yml
# Distributed under the LGPL-3.0 License: https://github.com/GregTechCEu/GregTech/blob/master/LICENSE

# Manages labels on PRs before allowing merging
name: Pull Request Labels

on:
  workflow_run:
    workflows: ["PR Labeler"]
    types:
      - completed
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize

# if a second commit is pushed quickly after the first, cancel the first one's build
concurrency:
  group: pr-labels-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  Labels:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: read # needed to utilize required-labels

    steps:
      - name: Check for Merge-Blocking Labels # blocks merge if present
        uses: mheap/github-action-required-labels@5847eef68201219cf0a4643ea7be61e77837bbce # 5.4.1
        with:
          mode: exactly
          count: 0
          labels: 'status: do not merge'
          exit_type: failure

      - name: Check for Required Labels # require at least one of these labels
        uses: mheap/github-action-required-labels@5847eef68201219cf0a4643ea7be61e77837bbce # 5.4.1
        with:
          mode: minimum
          count: 1
          labels: 'feature, bug, refactoring, translation, ignore changelog'
          exit_type: failure