name: Build and Run Dedicated Server

on:
  pull_request:

concurrency:
  group: run-dedicated-server-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  run-server:
    name: Run Dedicated Server
    runs-on: ubuntu-latest

    env:
      TIMEOUT: 600s

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      # if there are no changes in src/ or Gradle, skip the tests.
      - name: Check for changes in src and gradle files
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        id: filter # このステップの出力を後で参照できるようにidを設定
        with:
          filters: |
            src_or_gradle_changed:
              - 'src/**'
              - 'gradle/**'
              - '**.gradle'
              - 'gradlew.bat'
              - 'gradlew'

      - name: Grant execute permission for gradlew
        if: steps.filter.outputs.src_or_gradle_changed == 'true'
        shell: bash
        run: chmod +x gradlew

      - name: Setup Build
        if: steps.filter.outputs.src_or_gradle_changed == 'true'
        uses: ./.github/actions/build_setup

      - name: Run Dedicated Server
        if: steps.filter.outputs.src_or_gradle_changed == 'true'
        shell: bash
        run: |
          mkdir -p run/server
          echo "eula=true" > run/server/eula.txt
          echo "level-type=flat" > run/server/server.properties
          chmod +x ./.github/actions/run_server_autostop.sh
          timeout ${{ env.TIMEOUT }} ./.github/actions/run_server_autostop.sh | tee -a server.log || true

      - name: Test no errors reported during the server run
        if: steps.filter.outputs.src_or_gradle_changed == 'true'
        run: |
          chmod +x ./.github/actions/test_no_error_reports.sh
          ./.github/actions/test_no_error_reports.sh

      - name: Skip server run (no changes in src/ or Gradle)
        if: steps.filter.outputs.src_or_gradle_changed == 'false'
        run: |
          echo "No changes detected in src/ or Gradle. Server run is not required for this PR."
