name: Run Tests

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'src/**'
  pull_request:

concurrency:
  group: run-tests-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  run_test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      # if there are no changes in src/ or Gradle, skip the tests.
      - name: Check for changes in src and gradle files
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        id: filter # このステップの出力を後で参照できるようにidを設定
        with:
          filters: |
            src_or_gradle_changed:
              - 'src/**'
              - 'gradle/**'
              - '**.gradle'
              - 'gradlew.bat'
              - 'gradlew'

      - name: Setup Build
        if: steps.filter.outputs.src_or_gradle_changed == 'true'
        uses: ./.github/actions/build_setup

      - name: Run Tests with Gradle
        if: steps.filter.outputs.src_or_gradle_changed == 'true'
        run: ./gradlew test --warning-mode all --build-cache

      - name: Skip tests (no changes in src/ or Gradle)
        if: steps.filter.outputs.src_or_gradle_changed == 'false'
        run: |
          echo "No changes detected in src/ or Gradle. Tests are not required for this PR."