name: Run Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  run_test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Build
        uses: ./.github/actions/build_setup

      - name: Run Tests with Gradle
        run: ./gradlew test --warning-mode all --build-cache