name: Run printVersion Task
on:
  workflow_dispatch:

jobs:
  run-printversion:
    name: Run printVersion Task
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Setup Build
        uses: ./.github/actions/build_setup

      - name: Debug - raw printVersion output
        run: ./gradlew -q printVersion

      - name: Get Mod Version
        id: get_mod_version
        run: |
          set -euo pipefail
          VERSION=$(./gradlew -q printVersion | grep -E "^[0-9]+(\.[0-9]+)*-[0-9]+(\.[0-9]+)*$")
          echo "Version is $VERSION"
